export const qk = {
  shelves: () => ["shelves"] as const,
  shelf: (id: string) => ["shelf", id] as const,
  notebooksByShelf: (shelfId: string) => ["notebooks", "shelf", shelfId] as const,
  notebook: (id: string) => ["notebook", id] as const,
  recents: () => ["notebooks", "recent"] as const,
  notebookDoc: (id: string) => ["notebook", id, "doc"] as const,
  sources: (notebookId: string) => ["notebook", notebookId, "sources"] as const,
  sourceFileUrl: (sourceId: string) => ["source", sourceId, "file-url"] as const,
  annotations: (sourceId: string) => ["source", sourceId, "annotations"] as const,
  chatSessions: (notebookId: string) =>
    ["notebook", notebookId, "chat-sessions"] as const,
  chatSession: (sessionId: string) => ["chat-session", sessionId] as const,
  standaloneChatSessions: () => ["chat-sessions", "standalone"] as const,
  chapters: (notebookId: string) => ["notebook", notebookId, "chapters"] as const,
  chapter: (id: string) => ["chapter", id] as const,
  summary: (notebookId: string) => ["notebook", notebookId, "summary"] as const,
  summaryHistory: (notebookId: string) =>
    ["notebook", notebookId, "summaries"] as const,
  flashcards: (notebookId: string) => ["notebook", notebookId, "flashcards"] as const,
  quizzes: (notebookId: string) => ["notebook", notebookId, "quizzes"] as const,
  mindmaps: (notebookId: string) => ["notebook", notebookId, "mindmaps"] as const,
  mindmap: (id: string) => ["mindmap", id] as const,
  exam: (notebookId: string) => ["notebook", notebookId, "exam"] as const,
  podcast: (notebookId: string) => ["notebook", notebookId, "podcast"] as const,
  podcastAudio: (podcastId: string) => ["podcast", podcastId, "audio-url"] as const,
  me: () => ["me"] as const,
  usage: () => ["usage"] as const,
  subscription: () => ["subscription"] as const,
  archive: () => ["archive"] as const,
  creditPromoSubmissions: () => ["credit-promo-submissions"] as const,
  onboarding: () => ["onboarding"] as const,
}
